name: dalocale_example
description: Example code for the dalocale library.
version: 2.3.1
homepage: https://github.com/mauriciotogneri/dalocale

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  path: ^1.8.0

dev_dependencies:
  dalocale: ^2.3.1

  flutter_test:
    sdk: flutter