name: dalocale_example
description: Example code for the dalocale library.
version: 2.6.0
homepage: https://github.com/mauriciotogneri/dalocale

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  dalocale: ^2.5.0 # TODO: UPDATE TO 2.6.0

  flutter_test:
    sdk: flutter
