name: dalocale_example
description: Example code for the dalocale library.
version: 2.4.2
homepage: https://github.com/mauriciotogneri/dalocale

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  path: ^1.8.1

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_test:
    sdk: flutter

dev_dependencies:
  dalocale: ^2.4.2