name: dalocale_example
description: Example code for the dalocale library.
version: 1.0.0
author: Mauricio Togneri <mauricio.togneri@gmail.com>
homepage: https://github.com/mauriciotogneri/dalocale

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  path: ^1.6.4

dev_dependencies:

  flutter_test:
    sdk: flutter