name: dalocale
description: A Flutter package to easily support internationalization and localization in your project.
version: 2.0.0
homepage: https://github.com/mauriciotogneri/dalocale

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  path: ^1.7.0