name: dalocale
description: A Flutter package to easily support internationalization and localization in your project.
version: 2.5.0
homepage: https://github.com/mauriciotogneri/dalocale

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  collection: ^1.18.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter