name: dalocale
description: A Flutter package to easily support internationalization and localization in your project.
version: 2.3.2
homepage: https://github.com/mauriciotogneri/dalocale

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  collection: ^1.16.0
  path: ^1.8.1